<?php require_once(__DIR__ . '/../../middleware/permissao.php'); verificarPermissao(['Administrador', 'Bibliotecário', 'Bibliotecario']); require_once(__DIR__ . '/../../config/app.php'); ?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Atividades | TechLounged</title><link rel="stylesheet" href="<?= BASE_URL ?>/assets/css/techlounged.css"></head><body>
<?php include(__DIR__ . '/../../includes/topo.php'); ?>
<?php include(__DIR__ . '/../../includes/admin_sidebar.php'); ?>
<main class="tl-main"><div class="tl-admin-top"><div><h1>Atividades matriz</h1><p class="tl-meta">Cadastre os projetos base que poderão virar eventos na agenda pública.</p></div></div>
<section class="tl-card tl-card-pad" style="margin-bottom:18px;"><form id="formAtividade" class="tl-form-grid"><input type="hidden" id="id" name="id"><div class="tl-field tl-full"><label>Nome do projeto *</label><input type="text" id="nome_projeto" name="nome_projeto" required></div><div class="tl-field"><label>Eixo *</label><select id="id_eixo" name="id_eixo" required></select></div><div class="tl-field"><label>Periodicidade *</label><select id="id_periodicidade" name="id_periodicidade" required></select></div><div class="tl-field"><label>Público-alvo *</label><select id="id_publico_alvo" name="id_publico_alvo" required></select></div><div class="tl-field"><label>Imagem</label><input type="url" id="url_imagem" name="url_imagem" placeholder="https://..."></div><div class="tl-field tl-full"><label>Objetivo *</label><textarea id="objetivo" name="objetivo" required></textarea></div><div class="tl-field tl-full"><label>Observações</label><textarea id="observacoes_gerais" name="observacoes_gerais"></textarea></div><div class="tl-field tl-full"><label><input type="checkbox" id="eh_publico" name="eh_publico" value="1" checked> Visível ao público</label></div><div class="tl-actions tl-full"><button class="tl-btn tl-btn-primary" type="submit" id="btnSalvar">Salvar projeto</button><button class="tl-btn tl-btn-secondary" type="button" id="btnCancelar" style="display:none" onclick="resetarFormulario()">Cancelar edição</button></div></form></section>
<section class="tl-table-wrap"><table class="tl-table"><thead><tr><th>ID</th><th>Projeto</th><th>Eixo</th><th>Periodicidade</th><th>Público</th><th>Visível</th><th>Ações</th></tr></thead><tbody id="tabelaCorpo"></tbody></table></section></main></div>
<script src="<?= tl_url('assets/js/techlounged.js') ?>"></script><script>
const urlController = '<?= BASE_URL ?>/services/atividade_controle.php';
document.addEventListener('DOMContentLoaded', () => { carregarSelectsAuxiliares(); listar(); });
function carregarSelectsAuxiliares(){ fetch(`${urlController}?acao=auxiliares`).then(r=>r.json()).then(res=>{ if(!res.sucesso)return; popular('id_eixo',res.dados.eixos,'id','nome_eixo'); popular('id_periodicidade',res.dados.periodicidades,'id','descricao'); popular('id_publico_alvo',res.dados.publicos_alvo,'id','nome_publico'); }); }
function popular(id,arr,val,text){ const s=document.getElementById(id); s.innerHTML='<option value="">Selecione...</option>'; arr.forEach(i=>s.innerHTML+=`<option value="${i[val]}">${tlTextoSeguro(i[text])}</option>`); }
document.getElementById('formAtividade').addEventListener('submit',function(e){ e.preventDefault(); const acao=document.getElementById('id').value?'atualizar':'criar'; fetch(`${urlController}?acao=${acao}`,{method:'POST',body:new FormData(this)}).then(r=>r.json()).then(res=>{alert(res.mensagem); if(res.sucesso){resetarFormulario(); listar();}});});
function listar(){ fetch(`${urlController}?acao=listar`).then(r=>r.json()).then(res=>{ const c=document.getElementById('tabelaCorpo'); c.innerHTML=''; if(!res.sucesso||!res.dados.length){c.innerHTML='<tr><td colspan="7">Nenhuma atividade cadastrada.</td></tr>';return;} res.dados.forEach(i=>c.innerHTML+=`<tr><td>${i.id}</td><td><strong>${tlTextoSeguro(i.nome_projeto)}</strong></td><td>${tlTextoSeguro(i.nome_eixo)}</td><td>${tlTextoSeguro(i.nome_periodicidade)}</td><td>${tlTextoSeguro(i.nome_publico)}</td><td>${i.eh_publico==1?'Sim':'Não'}</td><td><button class="tl-btn tl-btn-secondary" onclick="editar(${i.id})">Editar</button> <button class="tl-btn tl-btn-danger" onclick="deletar(${i.id})">Excluir</button></td></tr>`); }); }
function editar(id){ fetch(`${urlController}?acao=buscar&id=${id}`).then(r=>r.json()).then(res=>{ if(!res.sucesso)return alert(res.mensagem); ['id','nome_projeto','id_eixo','id_periodicidade','id_publico_alvo','objetivo','observacoes_gerais','url_imagem'].forEach(k=>{const el=document.getElementById(k); if(el)el.value=res.dados[k]||'';}); document.getElementById('eh_publico').checked=res.dados.eh_publico==1; document.getElementById('btnCancelar').style.display='inline-flex'; document.getElementById('btnSalvar').innerText='Atualizar projeto'; }); }
function deletar(id){ if(!confirm('Deseja excluir esta atividade?'))return; fetch(`${urlController}?acao=deletar&id=${id}`).then(r=>r.json()).then(res=>{alert(res.mensagem); if(res.sucesso)listar();}); }
function resetarFormulario(){ document.getElementById('formAtividade').reset(); document.getElementById('id').value=''; document.getElementById('eh_publico').checked=true; document.getElementById('btnCancelar').style.display='none'; document.getElementById('btnSalvar').innerText='Salvar projeto'; }
</script></body></html>
