<?php require_once(__DIR__ . '/../../middleware/permissao.php'); verificarPermissao(['Administrador', 'Bibliotecário', 'Bibliotecario']); require_once(__DIR__ . '/../../config/app.php'); ?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Cine Biblioteca | TechLounged</title><link rel="stylesheet" href="<?= BASE_URL ?>/assets/css/techlounged.css"></head><body>
<?php include(__DIR__ . '/../../includes/topo.php'); ?>
<?php include(__DIR__ . '/../../includes/admin_sidebar.php'); ?>
<main class="tl-main"><div class="tl-admin-top"><div><h1>Cine Biblioteca</h1><p class="tl-meta">Vincule filmes e curtas aos registros de atividades do Cine Biblioteca.</p></div></div>
<section class="tl-card tl-card-pad" style="margin-bottom:18px;"><form id="formCine" class="tl-form-grid"><input type="hidden" id="id" name="id"><div class="tl-field tl-full"><label>Registro de atividade *</label><select id="id_registro_atividade" name="id_registro_atividade" required><option value="">Carregando...</option></select></div><div class="tl-field"><label>Título do curta *</label><input id="titulo_curta" name="titulo_curta" required></div><div class="tl-field"><label>Link</label><input type="url" id="link" name="link"></div><div class="tl-field tl-full"><label>Detalhes de controle</label><textarea id="detalhes_controle" name="detalhes_controle"></textarea></div><div class="tl-actions tl-full"><button class="tl-btn tl-btn-primary" type="submit" id="btnSalvar">Salvar</button><button class="tl-btn tl-btn-secondary" type="button" id="btnCancelar" style="display:none" onclick="resetarFormulario()">Cancelar edição</button></div></form></section>
<section class="tl-table-wrap"><table class="tl-table"><thead><tr><th>ID</th><th>Título</th><th>Atividade</th><th>Status</th><th>Link</th><th>Ações</th></tr></thead><tbody id="tabelaCorpo"></tbody></table></section></main></div>
<script src="<?= tl_url('assets/js/techlounged.js') ?>"></script><script>
const urlController='<?= BASE_URL ?>/services/cinebiblioteca_controle.php';
document.addEventListener('DOMContentLoaded',()=>{carregarAtividades(); listar();});
function carregarAtividades(){ fetch(`${urlController}?acao=auxiliares`).then(r=>r.json()).then(res=>{ if(!res.sucesso)return; const s=document.getElementById('id_registro_atividade'); s.innerHTML='<option value="">Selecione uma execução...</option>'; res.dados.registros_atividades.forEach(i=>s.innerHTML+=`<option value="${i.id}">${tlTextoSeguro(i.nome_projeto)} - ${tlDataBR(i.data_execucao)} [${tlTextoSeguro(i.status)}]</option>`); }); }
document.getElementById('formCine').addEventListener('submit',function(e){e.preventDefault(); const acao=document.getElementById('id').value?'atualizar':'criar'; fetch(`${urlController}?acao=${acao}`,{method:'POST',body:new FormData(this)}).then(r=>r.json()).then(res=>{alert(res.mensagem); if(res.sucesso){resetarFormulario(); listar();}});});
function listar(){ fetch(`${urlController}?acao=listar`).then(r=>r.json()).then(res=>{ const c=document.getElementById('tabelaCorpo'); c.innerHTML=''; if(!res.sucesso||!res.dados.length){c.innerHTML='<tr><td colspan="6">Nenhuma mídia cadastrada.</td></tr>';return;} res.dados.forEach(i=>c.innerHTML+=`<tr><td>${i.id}</td><td><strong>${tlTextoSeguro(i.titulo_curta)}</strong></td><td>${tlTextoSeguro(i.nome_projeto||'')}</td><td>${tlTextoSeguro(i.status||'')}</td><td>${i.link?`<a href="${tlTextoSeguro(i.link)}" target="_blank">Acessar</a>`:'-'}</td><td><button class="tl-btn tl-btn-secondary" onclick="editar(${i.id})">Editar</button> <button class="tl-btn tl-btn-danger" onclick="deletar(${i.id})">Excluir</button></td></tr>`); }); }
function editar(id){ fetch(`${urlController}?acao=buscar&id=${id}`).then(r=>r.json()).then(res=>{ if(!res.sucesso)return alert(res.mensagem); ['id','id_registro_atividade','titulo_curta','link','detalhes_controle'].forEach(k=>{const el=document.getElementById(k); if(el)el.value=res.dados[k]||'';}); document.getElementById('btnCancelar').style.display='inline-flex'; document.getElementById('btnSalvar').innerText='Atualizar'; }); }
function deletar(id){ if(!confirm('Deseja excluir esta mídia?'))return; fetch(`${urlController}?acao=deletar&id=${id}`).then(r=>r.json()).then(res=>{alert(res.mensagem); if(res.sucesso)listar();}); }
function resetarFormulario(){document.getElementById('formCine').reset(); document.getElementById('id').value=''; document.getElementById('btnCancelar').style.display='none'; document.getElementById('btnSalvar').innerText='Salvar';}
</script></body></html>
